ssl proxy module support ntls.
alibaba/tengine pull request #1637
Opened 2022-08-16 09:46 UTC by wa5i

rt

2022-08-16 09:46 UTC, wa5i commented
@dongbeiouba

2022-08-19 08:42 UTC, InfoHunter approved these changes

2022-08-29 07:29 UTC, dongbeiouba requested changes

2022-08-29 07:29 UTC, dongbeiouba commented on modules/ngx_openssl_ntls/t/ntls_proxy.t
> +my $openssl = $ENV{'TEST_OPENSSL_BINARY'} || "/opt/babassl/bin/openssl";
babassl -> tongsuo

2022-08-29 07:29 UTC, dongbeiouba commented on modules/ngx_openssl_ntls/t/ntls_proxy.t
> +			proxy_pass https://localhost:8082;
没对齐

2022-08-29 07:29 UTC, dongbeiouba commented on modules/ngx_openssl_ntls/t/ntls_proxy.t
> +			proxy_pass https://localhost:8082;
没对齐

2022-08-29 07:29 UTC, dongbeiouba commented on modules/ngx_openssl_ntls/t/stream_ntls_proxy.t
> +my $openssl = $ENV{'TEST_OPENSSL_BINARY'} || "/opt/babassl/bin/openssl";
babassl -> tongsuo

2022-08-29 07:29 UTC, dongbeiouba commented on src/stream/ngx_stream_proxy_module.c
> +    //conf->upstream.ssl_ciphers = conf->ssl_ciphers;
没用就删除吧

2022-08-29 07:29 UTC, dongbeiouba commented on modules/ngx_openssl_ntls/t/ntls_proxy.t
> +like($ret2, qr/^ssl_protocal=TLSv1\.2.*$/m, 'client -----(NTLSv1.1 ECC-SM2-SM4-GCM-SM3)-----> server(no proxy_enable_ntls) -----(TLSv1.2)-----> origin');
ret2是CBC，不是GCM

2022-10-23 03:42 UTC, chobits commented on src/http/modules/ngx_http_grpc_module.c
> +      NULL },
a newline should be appended under L465

2022-10-23 03:43 UTC, chobits commented on src/http/modules/ngx_http_proxy_module.c
> +      NULL },
newline need to be appended

2022-10-23 03:43 UTC, chobits commented on src/http/modules/ngx_http_uwsgi_module.c
> +      NULL },
newline

2022-10-23 03:43 UTC, chobits commented on src/stream/ngx_stream_proxy_module.c
> +      NULL },
\n

2022-11-11 10:25 UTC, wa5i commented on modules/ngx_openssl_ntls/t/ntls_proxy.t
> +my $openssl = $ENV{'TEST_OPENSSL_BINARY'} || "/opt/babassl/bin/openssl";
> babassl -> tongsuo

fixed

2022-11-11 10:25 UTC, wa5i commented on modules/ngx_openssl_ntls/t/ntls_proxy.t
> +			proxy_pass https://localhost:8082;
> 没对齐

fixed

2022-11-11 10:25 UTC, wa5i commented on src/stream/ngx_stream_proxy_module.c
> +    //conf->upstream.ssl_ciphers = conf->ssl_ciphers;
> 没用就删除吧

fixed

2022-11-11 10:25 UTC, wa5i commented on src/http/modules/ngx_http_grpc_module.c
> +      NULL },
> a newline should be appended under L465

fixed

2022-11-11 10:25 UTC, wa5i commented on modules/ngx_openssl_ntls/t/ntls_proxy.t
> +like($ret2, qr/^ssl_protocal=TLSv1\.2.*$/m, 'client -----(NTLSv1.1 ECC-SM2-SM4-GCM-SM3)-----> server(no proxy_enable_ntls) -----(TLSv1.2)-----> origin');
> ret2是CBC，不是GCM

fixed

2022-11-11 10:25 UTC, wa5i commented on src/http/modules/ngx_http_proxy_module.c
> +      NULL },
> newline need to be appended

fixed

2022-11-11 10:26 UTC, wa5i commented on src/stream/ngx_stream_proxy_module.c
> +      NULL },
> \n

fixed

2022-11-13 00:45 UTC, merged